---
title: "Lecture 1: Introduction"
subtitle: "<html><div style='float:left'></div><hr color='#EB811B' size=1px width=796px></html>"
author: Apoorva Lal | Stanford University
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  xaringan::moon_reader:
    css: [default, metropolis, metropolis-fonts]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
rm(list=ls())
options(htmltools.dir.version = FALSE)
library(knitr)
opts_chunk$set(
  fig.align="center",
  fig.height=4, #fig.width=6,
  dpi=300, #fig.path='Figs/',
  cache=T, echo=F, warning=F, message=F
  )

library(LalRUtils)
load_or_install(c('knitr','tidyverse','magrittr',
  'rio','data.table', 'stargazer'))
   #, "lib2"))
theme_set(lal_plot_theme())
set.seed(42)
####################################################
```

# Table of contents

1. [Sec1](#prologue)

2. [Sec2](#syllabus)


---
class: inverse, center, middle
name: prologue

# Prologue

<html><div style='float:left'></div><hr color='#EB811B' size=1px width=796px></html>

---

# Survey

Results from our [survey](https://goo.gl/forms/PjojERKMOpbo78JJ3)...

---
class: inverse, center, middle
name: syllabus

# Syllabus highlights

<html><div style='float:left'></div><hr color='#EB811B' size=1px width=796px></html>

(Read the full document [here](https://github.com/uo-ec607/syllabus/blob/master/syllabus.pdf).)

---

# ggplot2

```{r gapm_plot, dev="svg"}
library(ggplot2)
library(gapminder) ## For the gapminder data
ggplot(data = gapminder, mapping = aes(x = gdpPercap, y = lifeExp)) +
  geom_point()
```
