---
title       : "Template for Reveal JS Slides"
subtitle    :
author      : Apoorva Lal
institution : Stanford University
date        : July 2018
output:
  revealjs::revealjs_presentation:
    self_contained: true
    theme: moon
    transition: slide
    center : true
    highlight : zenburn
    reveal_options:
      slideNumber: true
      center : true
      help : true
      previewLinks: true
---



```{r setup, include=FALSE}
load_or_install(c('knitr', 'knitcitations'))
# set global chunk options
opts_chunk$set(cache=TRUE, warning = FALSE)

```
#  Constrained optimization

---

## Equality constraints

\[ \max f(x) \text{ s.t. } h(x) = c \]
where $f: \mathbb{R}^n \to \mathbb{R}$ and $h: \mathbb{R}^n \to \mathbb{R}^m$

---

## Equality constraints

Let $f:\mathbb{R}^n \to \mathbb{R}$ and $h: \mathbb{R}^n \to
\mathbb{R}^m$ be continuously differentiable. Suppose $x^*$ is a constrained
local maximizer of $f$ subject to $h(x) = c$. Also assume that
$Dh_{x^*}$ has rank $m$. Then there exists $\mu^* \in \mathbf{R}^m$ such
that $(x^*, \mu^*)$ is a critical point of the Lagrangian,
    $$
    L(x,\mu) = f(x) - \mu^T (h(x) - c).
    $$
i.e.
$$
\begin{aligned}
\frac{\partial L}{\partial x_i}(x^*,\mu^*) = & \frac{\partial
f}{\partial x_i} - {\mu^*}^T \frac{\partial h}{\partial
  x_i}(x^*) = 0 \\
 \frac{\partial L}{\partial \mu_j}(x^*,\mu^*) = & h(x^*) -
   c = 0
\end{aligned}
 $$
for $i = 1, ..., n$ and $j=1,...,m$.

---

## Inequality constraints

\[ \max_{x} f(x) \text{ s.t. } g(x) \leq b. \]

---

## Inequality constraints

Let $f:\mathbb{R}^n \to \mathbb{R}$ and $g: \mathbb{R}^n \to \mathbb{R}^m$ be continuously
differentiable. Suppose $x^*$ is a local maximizer of $f$ subject to
$g(x) \leq b$. Suppose that the first $k \leq m$ constraints, bind
\[ g_j(x^*) = b_j \]
for $j = 1 ... k$ and that the Jacobian for these constraints,
has rank $k$. Then, there exists
$\lambda^* \in \mathbb{R}^m$ such that for
\[ L(x,\lambda) = f(x) - \lambda^T (g(x) - b). \]
we have
$$
\begin{aligned}
\frac{\partial L}{\partial x_i}(x^*,\lambda^*) = & \frac{\partial
f}{\partial x_i} - {\lambda^*}^T \frac{\partial g}{\partial
x_i}(x^*) = 0 \\
\lambda_j^* \frac{\partial L}{\partial \lambda_j}(x^*,\lambda^*) =
    & \lambda_j^* \left(g_j(x^*) - b \right)= 0
\end{aligned}
$$
---

## Complementary slackness

For each $j$ if $\lambda_j^* > 0$ then $g_j(x^*) = b_j$ and if
  $g_j(x^*) < b$, then $\lambda_j^*=0$.

---

# Comparative statics

## Comparative statics

- Value function
$$
v(\theta) = \max_x f(x,\theta) \text{ s.t. } h(x,\theta) = c
$$
- Maximizer
$$
x^*(\theta) = \mathrm{arg}\max_x f(x,\theta) \text{ s.t. } h(x,\theta) = c
$$

---

## Envelope theorem

Let $f:\mathbb{R}^{n+k} \to \mathbb{R}$ and $h: \mathbb{R}^{n+k} \to
\mathbb{R}^m$ be continuously differentiable. Define
\[ v(\theta) = \max_x f(x,\theta) \text{ s.t. } h(x,\theta) = c \]
where $x \in \mathbb{R}^n$ and $\theta \in \mathbb{R}^k$. Then
\[ D_\theta v_\theta = D_\theta f_{x^*,\theta} - \mu^T D_\theta
h_{x^*,\theta} \]
where $\mu$ are the Lagrange multipliers, $D_\theta f_{x^*,\theta}$
denotes the $1 \times k$ matrix of partial derivatives of $f$ with
respect to $\theta$ evaluated at $(x^*,\theta)$ , and $D_\theta
h_{x^*,\theta}$ denotes the $m \times k$ matrix of partial derivatives
of $f$ with respect to $\theta$ evaluated at $(x^*,\theta)$.

---

## Example: consumer theory

> - Consumer choosing goods $x \in \mathbb{R}^n$ with prices $p$ and income $y$
> - Value function / indirect utility function
$$ v(p,y) = \max_x u(x) \text{ s.t. } p^T x - y \leq 0 $$
> - Expenditure minimization
$$ e(p,\bar{u}) = \min_x p^T x \text{ s.t. } u(x) \geq \bar{u} $$

---

## Example: producer theory

- Competitive multiple product firm facing output prices $p
  \in \mathbb{R}^k$ and input
  prices $w \in \mathbb{R}^n$
- Profits
  \[ \pi(p,w) = \max_{y,x} p^T y - w^T x \text{ s.t. } y - f(x) \leq
  0 \]
- Show supply slopes up and input demand slopes down, make extra
  assumptions about $f$ if needed

---

## Example: contracting with productivity shocks

- Firm production: $y = x f(h)$, $f$ increasing and concave
- Labor $h$, productivity $x \in \{x_H, x_L\}$
- Firm's problem with $x$ observed and contractible
$$ \max_{c(x), h(x)} \sum_{i \in \{H,L\}} q_i [x_i f(h_i)-c_i] $$
s.t.
$$ \sum_i q_i[U(c_i) + V(1-h_i)] \geq W_0 $$
- Show $c_H = c_L$ and $h_H > h_L$

---

## Example: contracting with productivity shocks

- Firm's problem with $x$ not-contractible, observed by firm but not worker
$$ \max_{c(x), h(x)} \sum_{i \in \{H,L\}} q_i [x_i f(h_i)-c_i] $$
s.t.
$$ \sum_i q_i[U(c_i) + V(1-h_i)] \geq W_0 $$
$$ x_L f(h_L) - c_L \geq x_L f(h_H) - c_H $$
$$ x_H f(h_H) - c_H \geq x_H f(h_L) - c_L $$

- Which constraint binds?
- Compare $c_i$ and $h_i$ with first-best contract

