---
title: "Punny Title"
subtitle: "Some explanation"
author:  'Apoorva Lal'
documentclass: amsart
amsart: true
thanks: "Acknowledgements: I'd like to thank my mum and dad"
date: \today
abstract: '\lipsum[4]'
output:
  pdf_document:
    keep_tex: true
    toc: false
    toc_depth : 2
    fig_width: 7
    fig_height: 6
    fig_caption: true
    template: /home/alal/Templates/boilerplate/lal-mdpdf.latex
    latex_engine: xelatex
fontsize: 12pt
colorlinks: true
indent: true
xetex: true
mathspec: true
# numbersections: true
backend: biber
bibliography: /home/alal/Dropbox/MyLibrary.bib
csl: econometrica.csl
header-includes:
  - '\usepackage{lipsum}'
---


```{r, echo=FALSE, include=FALSE}
####################################################
rm(list=ls())
load_or_install(c('knitr','tidyverse','magrittr',
  'rio','data.table', 'stargazer'))
   #, "lib2"))
sessionInfo()
theme_set(theme_minimal())
####################################################

opts_chunk$set(echo=F, autodep=TRUE, cache.comments=FALSE,
               message=FALSE, warning=FALSE)

```

# Introduction

@Deatonanalysishouseholdsurveys1997

# Model

$$
max_{x} \int_{-\infty}^{\infty} \beta^t U(c_t) dt
$$

# Data

```{r}
#%%
ggplot(mpg, aes(displ, hwy, colour = class)) +
  geom_point()
#%%
```

# Results

```{r}
lm1 = lm(hwy ~ cyl + factor(class), data=mpg)
```

```{r, results='asis'}
stargazer(lm1, header=F, type='latex')
```

\newpage

# Bibliography
