---
title: "Title"
author:  'Apoorva Lal'
date: \today
output:
  pdf_document:
    keep_tex: true
    toc: false
    toc_depth : 2
    fig_width: 7
    fig_height: 6
    fig_caption: true
    df_print: kable
    dev: cairo_pdf
    latex_engine: xelatex
fontsize: 12pt
colorlinks: true
indent: true
xetex: true
# mainfont: "Linux Libertine O"
mainfont: "Utopia"
monofont: Iosevka
mathspec: true
geometry: margin=2cm
numbersections: true
header-includes:
  # - \setmainfont{Museo}
---

```{r, echo=FALSE, include=FALSE}
# %% ####################################################
rm(list = ls())
library(LalRUtils)
LalRUtils::libreq(tidyverse, data.table, stargazer2, lfe, rio, foreach, magrittr, janitor)
theme_set(lal_plot_theme())
options(repr.plot.width=12, repr.plot.height=9)
set.seed(42)
# %% ####################################################
opts_chunk$set(echo=F, autodep=TRUE, cache.comments=FALSE,
               message=FALSE, warning=FALSE)

```

# Introduction

# Model

$$
max_{x} \int_{-\infty}^{\infty} \beta^t U(c_t) dt
$$

# Data

```{r}
#%%
ggplot(mpg, aes(displ, hwy, colour = class)) +
  geom_point()
#%%
```

# Results

```{r}
lm1 = lm(hwy ~ cyl + factor(class), data=mpg)
```

```{r, results='asis'}
stargazer(lm1, header=F, type='latex')
```
