---
title: "test"
description: |
  A step by step guide to calculating direct standard errors.
author:
  - name: Apoorva Lal
    affiliation: Stanford
# bibliography: spatial_se.bib

date: "`r Sys.Date()`"
output:
  distill::distill_article:
    toc: true
    toc_depth: 1

---

```{r global_options, include=FALSE}
# %% ####################################################
rm(list = ls())
library(LalRUtils)
LalRUtils::libreq(tidyverse, data.table, stargazer2, knitr, kableExtra,
                  rmarkdown, lfe, rio, foreach, magrittr, janitor)
theme_set(lal_plot_theme())
options(repr.plot.width=12, repr.plot.height=9)
set.seed(42)
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
                      cache=TRUE, echo=FALSE, warning=FALSE, message=FALSE)
# %% ####################################################
```

# Introduction

```{r}
x = 1:10
x
```

The quick brown fox jumped over the lazy dog.

<aside>
the dog's laziness is a stereotype.
</aside>

# Figures
```{r, layout="l-body-outset", fig.width=6, fig.height=1.5}
library(ggplot2)
ggplot(diamonds, aes(carat, price)) + geom_smooth() +
  facet_grid(~ cut)
```

<aside>
```{r}
ggplot(mtcars, aes(hp, mpg)) + geom_point() + geom_smooth()
```
</aside>

# Tables
```{r, layout="l-body-outset"}
paged_table(mtcars)
```

# Widgets

```{r}
libreq(leaflet)
leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=174.768, lat=-36.852, popup="The birthplace of R")
```

```{r, layout="l-page", fig.height=3}
libreq(dygraphs)
dygraph(ldeaths)
```
